// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5xatO20W-zBSDBUBR-epuHiETkm6NZk',
    appId: '1:813161449252:android:9817a06d8a792b7a9d95b1',
    messagingSenderId: '813161449252',
    projectId: 'loveonlife-678ee',
    storageBucket: 'loveonlife-678ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5R67PEKT--G069N03VRsYYE6kYQ7ss3Q',
    appId: '1:813161449252:ios:f698ad1d4e41b9199d95b1',
    messagingSenderId: '813161449252',
    projectId: 'loveonlife-678ee',
    storageBucket: 'loveonlife-678ee.firebasestorage.app',
    androidClientId: '813161449252-7iv5shde1mate94df2v2o76geeun4amh.apps.googleusercontent.com',
    iosClientId: '813161449252-eq01riueph9mjsgnkkg17f9g2ci7mcqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveOnLife',
  );

}